Exception occured while processing batch "<%= @batch %>", job "<%= @job %>":
<%= @exception.inspect %>
