Exception occured while uploading results of batch "<%= @batch %>", job "<%= @job %>":
<%= @exception.inspect %>
